# -*- coding: utf-8 -*-
import pyperclip

a = """Ldrt	TerrainArt\\LordaeronSummer	Lords_Dirt
Ldro	TerrainArt\\LordaeronSummer	Lords_DirtRough
Ldrg	TerrainArt\\LordaeronSummer	Lords_DirtGrass
Lrok	TerrainArt\\LordaeronSummer	Lords_Rock
Lgrs	TerrainArt\\LordaeronSummer	Lords_Grass
Lgrd	TerrainArt\\LordaeronSummer	Lords_GrassDark
Fdrt	TerrainArt\\LordaeronFall	Lordf_Dirt
Fdro	TerrainArt\\LordaeronFall	Lordf_DirtRough
Fdrg	TerrainArt\\LordaeronFall	Lordf_DirtGrass
Frok	TerrainArt\\LordaeronFall	Lordf_Rock
Fgrs	TerrainArt\\LordaeronFall	Lordf_Grass
Fgrd	TerrainArt\\LordaeronFall	Lordf_GrassDark
Wdrt	TerrainArt\\LordaeronWinter	Lordw_Dirt
Wdro	TerrainArt\\LordaeronWinter	Lordw_DirtRough
Wsng	TerrainArt\\LordaeronWinter	Lordw_SnowGrass
Wrok	TerrainArt\\LordaeronWinter	Lordw_Rock
Wgrs	TerrainArt\\LordaeronWinter	Lordw_Grass
Wsnw	TerrainArt\\LordaeronWinter	Lordw_Snow
Bdrt	TerrainArt\\Barrens	Barrens_Dirt
Bdrh	TerrainArt\\Barrens	Barrens_DirtRough
Bdrr	TerrainArt\\Barrens	Barrens_Pebbles
Bdrg	TerrainArt\\Barrens	Barrens_DirtGrass
Bdsr	TerrainArt\\Barrens	Barrens_Desert
Bdsd	TerrainArt\\Barrens	Barrens_DesertDark
Bflr	TerrainArt\\Barrens	Barrens_Rock
Bgrr	TerrainArt\\Barrens	Barrens_Grass
Adrt	TerrainArt\\Ashenvale	Ashen_Dirt
Adrd	TerrainArt\\Ashenvale	Ashen_DirtRough
Agrs	TerrainArt\\Ashenvale	Ashen_Grass
Arck	TerrainArt\\Ashenvale	Ashen_Rock
Agrd	TerrainArt\\Ashenvale	Ashen_GrassLumpy
Avin	TerrainArt\\Ashenvale	Ashen_Vines
Adrg	TerrainArt\\Ashenvale	Ashen_DirtGrass
Alvd	TerrainArt\\Ashenvale	Ashen_leaves
Cdrt	TerrainArt\\Felwood	Felwood_Dirt
Cdrd	TerrainArt\\Felwood	Felwood_DirtRough
Cpos	TerrainArt\\Felwood	Felwood_Poison
Crck	TerrainArt\\Felwood	Felwood_Rock
Cvin	TerrainArt\\Felwood	Felwood_Vines
Cgrs	TerrainArt\\Felwood	Felwood_Grass
Clvg	TerrainArt\\Felwood	Felwood_Leaves
Ndrt	TerrainArt\\Northrend	North_dirt
Ndrd	TerrainArt\\Northrend	North_dirtdark
Nrck	TerrainArt\\Northrend	North_rock
Ngrs	TerrainArt\\Northrend	North_Grass
Nice	TerrainArt\\Northrend	North_ice
Nsnw	TerrainArt\\Northrend	North_Snow
Nsnr	TerrainArt\\Northrend	North_SnowRock
Ydrt	TerrainArt\\Cityscape	City_Dirt
Ydtr	TerrainArt\\Cityscape	City_DirtRough
Yblm	TerrainArt\\Cityscape	City_BlackMarble
Ybtl	TerrainArt\\Cityscape	City_BrickTiles
Ysqd	TerrainArt\\Cityscape	City_SquareTiles
Yrtl	TerrainArt\\Cityscape	City_RoundTiles
Ygsb	TerrainArt\\Cityscape	City_Grass
Yhdg	TerrainArt\\Cityscape	City_GrassTrim
Ywmb	TerrainArt\\Cityscape	City_WhiteMarble
Vdrt	TerrainArt\\Village	Village_Dirt
Vdrr	TerrainArt\\Village	Village_DirtRough
Vcrp	TerrainArt\\Village	Village_Crops
Vcbp	TerrainArt\\Village	Village_CobblePath
Vstp	TerrainArt\\Village	Village_StonePath
Vgrs	TerrainArt\\Village	Village_GrassShort
Vrck	TerrainArt\\Village	Village_Rocks
Vgrt	TerrainArt\\Village	Village_GrassThick
Qdrt	TerrainArt\\VillageFall	VillageFall_Dirt
Qdrr	TerrainArt\\VillageFall	VillageFall_DirtRough
Qcrp	TerrainArt\\VillageFall	VillageFall_Crops
Qcbp	TerrainArt\\VillageFall	VillageFall_CobblePath
Qstp	TerrainArt\\VillageFall	VillageFall_StonePath
Qgrs	TerrainArt\\VillageFall	VillageFall_GrassShort
Qrck	TerrainArt\\VillageFall	VillageFall_Rocks
Qgrt	TerrainArt\\VillageFall	VillageFall_GrassThick
Xdrt	TerrainArt\\Dalaran	Dalaran_Dirt
Xdtr	TerrainArt\\Dalaran	Dalaran_DirtRough
Xblm	TerrainArt\\Dalaran	Dalaran_BlackMarble
Xbtl	TerrainArt\\Dalaran	Dalaran_BrickTiles
Xsqd	TerrainArt\\Dalaran	Dalaran_SquareTiles
Xrtl	TerrainArt\\Dalaran	Dalaran_RoundTiles
Xgsb	TerrainArt\\Dalaran	Dalaran_Grass
Xhdg	TerrainArt\\Dalaran	Dalaran_GrassTrim
Xwmb	TerrainArt\\Dalaran	Dalaran_WhiteMarble
Ddrt	TerrainArt\\Dungeon	Cave_Dirt
Dbrk	TerrainArt\\Dungeon	Cave_Brick
Drds	TerrainArt\\Dungeon	Cave_RedStones
Dlvc	TerrainArt\\Dungeon	Cave_LavaCracks
Dlav	TerrainArt\\Dungeon	Cave_Lava
Ddkr	TerrainArt\\Dungeon	Cave_DarkRocks
Dgrs	TerrainArt\\Dungeon	Cave_GreyStones
Dsqd	TerrainArt\\Dungeon	Cave_SquareTiles
Gdrt	TerrainArt\\Dungeon2	GDirt
Gbrk	TerrainArt\\Dungeon2	GBrick
Grds	TerrainArt\\Dungeon2	GRedStones
Glvc	TerrainArt\\Dungeon2	GLavaCracks
Glav	TerrainArt\\Dungeon2	GLava
Gdkr	TerrainArt\\Dungeon2	GDarkRocks
Ggrs	TerrainArt\\Dungeon2	GGreyStones
Gsqd	TerrainArt\\Dungeon2	GSquareTiles
Zdrt	TerrainArt\\Ruins	Ruins_Dirt
Zdtr	TerrainArt\\Ruins	Ruins_DirtRough
Zdrg	TerrainArt\\Ruins	Ruins_DirtGrass
Zbks	TerrainArt\\Ruins	Ruins_SmallBricks
Zsan	TerrainArt\\Ruins	Ruins_Sand
Zbkl	TerrainArt\\Ruins	Ruins_LargeBricks
Ztil	TerrainArt\\Ruins	Ruins_RoundTiles
Zgrs	TerrainArt\\Ruins	Ruins_Grass
Zvin	TerrainArt\\Ruins	Ruins_GrassDark
Idrt	TerrainArt\\Icecrown	Ice_Dirt
Idtr	TerrainArt\\Icecrown	Ice_DirtRough
Idki	TerrainArt\\Icecrown	Ice_DarkIce
Ibkb	TerrainArt\\Icecrown	Ice_BlackBricks
Irbk	TerrainArt\\Icecrown	Ice_RuneBricks
Itbk	TerrainArt\\Icecrown	Ice_TiledBricks
Iice	TerrainArt\\Icecrown	Ice_Ice
Ibsq	TerrainArt\\Icecrown	Ice_BlackSquares
Isnw	TerrainArt\\Icecrown	Ice_Snow
Odrt	TerrainArt\\Outland	Outland_Dirt
Odtr	TerrainArt\\Outland	Outland_DirtLight
Osmb	TerrainArt\\Outland	Outland_RoughDirt
Ofst	TerrainArt\\Outland	Outland_DirtCracked
Olgb	TerrainArt\\Outland	Outland_FlatStones
Orok	TerrainArt\\Outland	Outland_Rock
Ofsl	TerrainArt\\Outland	Outland_FlatStonesLight
Oaby	TerrainArt\\Outland	Outland_Abyss
Kdrt	TerrainArt\\BlackCitadel	Citadel_Dirt
Kfsl	TerrainArt\\BlackCitadel	Citadel_DirtLight
Kdtr	TerrainArt\\BlackCitadel	Citadel_RoughDirt
Kfst	TerrainArt\\BlackCitadel	Citadel_FlatStones
Ksmb	TerrainArt\\BlackCitadel	Citadel_SmallBricks
Klgb	TerrainArt\\BlackCitadel	Citadel_LargeBricks
Ksqt	TerrainArt\\BlackCitadel	Citadel_SquareTiles
Kdkt	TerrainArt\\BlackCitadel	Citadel_DarkTiles
Jdrt	TerrainArt\\DalaranRuins	DRuins_Dirt
Jdtr	TerrainArt\\DalaranRuins	DRuins_DirtRough
Jblm	TerrainArt\\DalaranRuins	DRuins_BlackMarble
Jbtl	TerrainArt\\DalaranRuins	DRuins_BrickTiles
Jsqd	TerrainArt\\DalaranRuins	DRuins_SquareTiles
Jrtl	TerrainArt\\DalaranRuins	DRuins_RoundTiles
Jgsb	TerrainArt\\DalaranRuins	DRuins_Grass
Jhdg	TerrainArt\\DalaranRuins	DRuins_GrassTrim
Jwmb	TerrainArt\\DalaranRuins	DRuins_WhiteMarble
cAc2	TerrainArt\\Ashenvale	Ashen_Dirt
cAc1	TerrainArt\\Ashenvale	Ashen_Grass
cBc2	TerrainArt\\Barrens	Barrens_Desert
cBc1	TerrainArt\\Barrens	Barrens_Grass
cKc1	TerrainArt\\BlackCitadel	Citadel_Dirt
cKc2	TerrainArt\\BlackCitadel	Citadel_DarkTiles
cYc2	TerrainArt\\Cityscape	City_Dirt
cYc1	TerrainArt\\Cityscape	City_SquareTiles
cXc2	TerrainArt\\Dalaran	Dalaran_Dirt
cXc1	TerrainArt\\Dalaran	Dalaran_SquareTiles
cJc2	TerrainArt\\DalaranRuins	DRuins_Dirt
cJc1	TerrainArt\\DalaranRuins	DRuins_SquareTiles
cDc2	TerrainArt\\Dungeon	Cave_Dirt
cDc1	TerrainArt\\Dungeon	Cave_SquareTiles
cCc2	TerrainArt\\Felwood	Felwood_Dirt
cCc1	TerrainArt\\Felwood	Felwood_Grass
cIc2	TerrainArt\\Icecrown	Ice_RuneBricks
cIc1	TerrainArt\\Icecrown	Ice_Snow
cFc2	TerrainArt\\LordaeronFall	Lordf_Dirt
cFc1	TerrainArt\\LordaeronFall	Lordf_Grass
cLc2	TerrainArt\\LordaeronSummer	Lords_Dirt
cLc1	TerrainArt\\LordaeronSummer	Lords_Grass
cWc2	TerrainArt\\LordaeronWinter	Lordw_Grass
cWc1	TerrainArt\\LordaeronWinter	Lordw_Snow
cNc2	TerrainArt\\Northrend	North_dirt
cNc1	TerrainArt\\Northrend	North_Snow
cOc1	TerrainArt\\Outland	Outland_Abyss
cOc2	TerrainArt\\Outland	Outland_RoughDirt
cZc2	TerrainArt\\Ruins	Ruins_Dirt
cZc1	TerrainArt\\Ruins	Ruins_LargeBricks
cGc2	TerrainArt\\Dungeon2	GDirt
cGc1	TerrainArt\\Dungeon2	GSquareTiles
cVc2	TerrainArt\\Village	Village_Dirt
cVc1	TerrainArt\\Village	Village_GrassThick
cQc2	TerrainArt\\VillageFall	VillageFall_Dirt
cQc1	TerrainArt\\VillageFall	VillageFall_GrassThick"""

# pyperclip.copy(path)
result = []
for line in a.split('\n'):
    rawcode, folder, file = line.split()
    result.append(f"set Tile('{rawcode}').file = \"{folder}\\{file}.blp\"")
pyperclip.copy('\n'.join(result).replace('\\', '\\\\'))
